# Generated by Django 2.1.3 on 2018-12-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='ProductsModel',
        ),
    ]
